export const THAI_PHRASES = [
  { id: "thai-001", thai: "สวัสดี", romanization: "sà-wàt-dii", chinese: "你好" },
  { id: "thai-002", thai: "ขอบคุณ", romanization: "khàawp-khun", chinese: "谢谢" },
  { id: "thai-003", thai: "ขอโทษ", romanization: "khǎaw-thôot", chinese: "对不起" },
  { id: "thai-004", thai: "ไม่เป็นไร", romanization: "mâi-pen-rai", chinese: "没关系" },
  { id: "thai-005", thai: "ใช่", romanization: "châi", chinese: "是" },
  { id: "thai-006", thai: "ไม่ใช่", romanization: "mâi-châi", chinese: "不是" },
  { id: "thai-007", thai: "ได้", romanization: "dâai", chinese: "可以" },
  { id: "thai-008", thai: "ไม่ได้", romanization: "mâi-dâai", chinese: "不可以" },
  { id: "thai-009", thai: "เท่าไหร่", romanization: "thâo-rài", chinese: "多少钱" },
  { id: "thai-010", thai: "ราคาเท่าไหร่", romanization: "raa-khaa thâo-rài", chinese: "价格是多少" },
  { id: "thai-011", thai: "ลดราคาได้ไหม", romanization: "lót raa-khaa dâai mái", chinese: "可以便宜一点吗" },
  { id: "thai-012", thai: "เอาอันนี้", romanization: "ao an níi", chinese: "要这个" },
  { id: "thai-013", thai: "ไม่เอา", romanization: "mâi-ao", chinese: "不要" },
  { id: "thai-014", thai: "มีไหม", romanization: "mii mái", chinese: "有吗" },
  { id: "thai-015", thai: "ห้องน้ำอยู่ที่ไหน", romanization: "hâawng-náam yùu thîi-nǎi", chinese: "洗手间在哪里" },
  { id: "thai-016", thai: "ไปสนามบิน", romanization: "bpai sà-nǎam-bin", chinese: "去机场" },
  { id: "thai-017", thai: "ไปโรงแรม", romanization: "bpai roong-raem", chinese: "去酒店" },
  { id: "thai-018", thai: "ไปสถานีรถไฟ", romanization: "bpai sà-thǎa-nii rót-fai", chinese: "去火车站" },
  { id: "thai-019", thai: "ไปโรงพยาบาล", romanization: "bpai roong-phá-yaa-baan", chinese: "去医院" },
  { id: "thai-020", thai: "กรุณาไปที่นี่", romanization: "gà-rú-naa bpai thîi-nîi", chinese: "请去这里" },
  { id: "thai-021", thai: "เลี้ยวซ้าย", romanization: "líao sáai", chinese: "左转" },
  { id: "thai-022", thai: "เลี้ยวขวา", romanization: "líao khwǎa", chinese: "右转" },
  { id: "thai-023", thai: "ตรงไป", romanization: "dtrong bpai", chinese: "直走" },
  { id: "thai-024", thai: "หยุดตรงนี้", romanization: "yùt dtrong níi", chinese: "在这里停" },
  { id: "thai-025", thai: "เรียกแท็กซี่ให้หน่อย", romanization: "rîiak tháek-sîi hâi nòi", chinese: "请帮我叫出租车" },
  { id: "thai-026", thai: "ฉันหิว", romanization: "chǎn hǐu", chinese: "我饿了" },
  { id: "thai-027", thai: "ฉันกระหายน้ำ", romanization: "chǎn grà-hǎai náam", chinese: "我渴了" },
  { id: "thai-028", thai: "ขอเมนูหน่อย", romanization: "khǎaw mee-nuu nòi", chinese: "请给我菜单" },
  { id: "thai-029", thai: "ไม่เผ็ด", romanization: "mâi phèt", chinese: "不辣" },
  { id: "thai-030", thai: "เผ็ดน้อย", romanization: "phèt náawy", chinese: "少辣" },
  { id: "thai-031", thai: "อร่อยมาก", romanization: "à-ròi mâak", chinese: "很好吃" },
  { id: "thai-032", thai: "ขอน้ำเปล่า", romanization: "khǎaw náam bplào", chinese: "请给我白水" },
  { id: "thai-033", thai: "คิดเงินด้วย", romanization: "khít ngoen dûai", chinese: "请结账" },
  { id: "thai-034", thai: "ฉันแพ้อาหารทะเล", romanization: "chǎn pháae aa-hǎan thá-lee", chinese: "我海鲜过敏" },
  { id: "thai-035", thai: "มีห้องว่างไหม", romanization: "mii hâawng wâang mái", chinese: "有空房吗" },
  { id: "thai-036", thai: "ฉันจองไว้แล้ว", romanization: "chǎn jaawng wái láaeo", chinese: "我已经预订了" },
  { id: "thai-037", thai: "ขอเช็คอิน", romanization: "khǎaw chék-in", chinese: "我要办理入住" },
  { id: "thai-038", thai: "ขอเช็คเอาท์", romanization: "khǎaw chék-ao", chinese: "我要退房" },
  { id: "thai-039", thai: "มีไวไฟไหม", romanization: "mii wai-fai mái", chinese: "有无线网络吗" },
  { id: "thai-040", thai: "รหัสไวไฟคืออะไร", romanization: "rá-hàt wai-fai kheu à-rai", chinese: "无线网络密码是什么" },
  { id: "thai-041", thai: "ช่วยด้วย", romanization: "chûai dûai", chinese: "救命" },
  { id: "thai-042", thai: "ฉันไม่สบาย", romanization: "chǎn mâi sà-baai", chinese: "我不舒服" },
  { id: "thai-043", thai: "ฉันเจ็บหัว", romanization: "chǎn jèp hǔa", chinese: "我头疼" },
  { id: "thai-044", thai: "ฉันต้องการหมอ", romanization: "chǎn dtâawng-gaan mǎaw", chinese: "我需要医生" },
  { id: "thai-045", thai: "โทรเรียกตำรวจ", romanization: "thoo rîiak dtam-rùat", chinese: "打电话叫警察" },
  { id: "thai-046", thai: "หนังสือเดินทางหาย", romanization: "nǎng-sěu doen-thaang hǎai", chinese: "护照丢了" },
  { id: "thai-047", thai: "ฉันมาจากจีน", romanization: "chǎn maa jàak jiin", chinese: "我来自中国" },
  { id: "thai-048", thai: "ฉันพูดไทยไม่เก่ง", romanization: "chǎn phûut thai mâi gèng", chinese: "我泰语说得不好" },
  { id: "thai-049", thai: "พูดช้าหน่อย", romanization: "phûut cháa nòi", chinese: "请说慢一点" },
  { id: "thai-050", thai: "ช่วยเขียนให้หน่อย", romanization: "chûai khǐian hâi nòi", chinese: "请帮我写下来" },
  { id: "thai-051", thai: "วันนี้", romanization: "wan-níi", chinese: "今天" },
  { id: "thai-052", thai: "พรุ่งนี้", romanization: "phrûng-níi", chinese: "明天" },
  { id: "thai-053", thai: "เมื่อวาน", romanization: "mûuea-waan", chinese: "昨天" },
  { id: "thai-054", thai: "ตอนนี้", romanization: "dtaawn-níi", chinese: "现在" },
  { id: "thai-055", thai: "กี่โมง", romanization: "gìi moong", chinese: "几点" },
  { id: "thai-056", thai: "หนึ่ง", romanization: "nèung", chinese: "一" },
  { id: "thai-057", thai: "สอง", romanization: "sǎawng", chinese: "二" },
  { id: "thai-058", thai: "สาม", romanization: "sǎam", chinese: "三" },
  { id: "thai-059", thai: "สี่", romanization: "sìi", chinese: "四" },
  { id: "thai-060", thai: "ห้า", romanization: "hâa", chinese: "五" },
  { id: "thai-061", thai: "สิบ", romanization: "sìp", chinese: "十" },
  { id: "thai-062", thai: "ร้อย", romanization: "ráawy", chinese: "百" },
  { id: "thai-063", thai: "พัน", romanization: "phan", chinese: "千" },
  { id: "thai-064", thai: "ฉันอยากซื้อซิมการ์ด", romanization: "chǎn yàak súue sim-gaad", chinese: "我想买电话卡" },
  { id: "thai-065", thai: "เติมเงินได้ที่ไหน", romanization: "dteem ngoen dâai thîi-nǎi", chinese: "在哪里充值" },
  { id: "thai-066", thai: "มีที่ชาร์จไหม", romanization: "mii thîi châat mái", chinese: "有充电器吗" },
  { id: "thai-067", thai: "ฉันหลงทาง", romanization: "chǎn lǒng thaang", chinese: "我迷路了" },
  { id: "thai-068", thai: "อยู่ใกล้ไหม", romanization: "yùu glâi mái", chinese: "近吗" },
  { id: "thai-069", thai: "ไกลไหม", romanization: "glai mái", chinese: "远吗" },
  { id: "thai-070", thai: "ขอถุงหน่อย", romanization: "khǎaw thǔng nòi", chinese: "请给我袋子" },
  { id: "thai-071", thai: "จ่ายด้วยบัตรได้ไหม", romanization: "jàai dûai bàt dâai mái", chinese: "可以刷卡吗" },
  { id: "thai-072", thai: "รับเงินสดไหม", romanization: "ráp ngoen sòt mái", chinese: "收现金吗" },
  { id: "thai-073", thai: "ฉันต้องการใบเสร็จ", romanization: "chǎn dtâawng-gaan bai-sèt", chinese: "我需要收据" },
  { id: "thai-074", thai: "เปิดกี่โมง", romanization: "bpòet gìi moong", chinese: "几点开门" },
  { id: "thai-075", thai: "ปิดกี่โมง", romanization: "bpìt gìi moong", chinese: "几点关门" },
  { id: "thai-076", thai: "ฉันอยากไปทะเล", romanization: "chǎn yàak bpai thá-lee", chinese: "我想去海边" },
  { id: "thai-077", thai: "ถ่ายรูปให้หน่อย", romanization: "thàai rûup hâi nòi", chinese: "请帮我拍照" },
  { id: "thai-078", thai: "สวยมาก", romanization: "sǔai mâak", chinese: "很漂亮" },
  { id: "thai-079", thai: "ร้อนมาก", romanization: "ráawn mâak", chinese: "很热" },
  { id: "thai-080", thai: "ฝนตก", romanization: "fǒn dtòk", chinese: "下雨" }
];
